// Ruby Blue v0.1.0
// This theme is generated by a converter script.
// Original Textmate theme: Ruby Blue by John W. Long.
// The conversion is still incomplete. Any suggestions or any problems,
// please contact me at yanyu [at] cyblogic [dot] com.

PacuEditorFG = '#FFFFFF';
PacuEditorBG = '#121E31';
PacuEditorCursor = '#fff';
PacuEditorSelection = '#38566F';
PacuEditorMatch = '#787878';
PacuEditorBracketMatch = PacuEditorMatch;
PacuEditorCurrentLine = '#253E5A';
PacuComment = '#428BDD';
PacuBlockComment = '#438AD7';
PacuHtmlComment = '#428BDD';
PacuString = '#1DC116';
PacuStringLiteral = '#E2CE00';
PacuRegularExpression = '#CA4344';
PacuInterpolation = '#468434';
PacuRubyInterpolation = '#468434';
PacuChar = '#1DC116';
PacuDocument = '#1DC116';
PacuNumber = '#EDDD3D';
PacuRubyNumber = '#EDDD3D';
PacuInteger = '#EDDD3D';
PacuFloat = '#EDDD3D';
PacuKeyword = '#F8BB00';
PacuJavascriptKeyword = '#F8BB00';
PacuObjcKeyword = '#F8BB00';
PacuPreprocessing = '#FFFFFF';
PacuBuiltinConstant = '#8AA6C1';
PacuEscape = '#EDDD37';
PacuBlock = '#FFFFFF';
PacuSymbol = '#B53B3C';
PacuVariable = '#FFFFFF';
PacuRubyVariable = '#FFFFFF';
PacuPunctuator = '#FFFFFF';
PacuOperator = '#8AA6C1';
PacuArrayBracket = '#FFFFFF';
PacuBackslashSequence = '#FFFFFF';
PacuTag = '#FFFFFF';
PacuTagName = '#FFFFFF';
PacuTagOpen = '#FFFFFF';
PacuTagClose = '#FFFFFF';
PacuTagOther = '#FFFFFF';
PacuTagAttribute = '#FFFFFF';
PacuTagValue = '#FFFFFF';
PacuErbTag = '#FFFFFF';

charcoal.themes["Ruby Blue"] =
{
	displayName: "Ruby Blue",

	layers: {
		"ruby": {
			"Comment": PacuComment,
			"BlockComment": PacuBlockComment,
			"Keyword": PacuKeyword,
			"DeclarationKeyword": PacuKeyword,
			"Builtin": PacuBuiltinConstant,
			"String": PacuString,
			"EscapeSequence": PacuEscape,
			"Interpolation": PacuInterpolation,
			"Block": PacuBlock,
			"Document": PacuDocument,
			"Integer": PacuInteger,
			"Float": PacuFloat,
			"Symbol": PacuSymbol,
			"ObjectName": PacuRubyVariable,
			"Operator": PacuOperator,
			"OpeningBracket": PacuArrayBracket,
			"ClosingBracket": PacuArrayBracket
		},
		"python": {
			"Comment": PacuComment,
			"String": PacuString,
			"Keyword": PacuKeyword,
			"Identifier": PacuKeyword,
			"Operator": PacuOperator,
			"Float": PacuFloat,
			"Integer": PacuInteger
		},
		"javascript": {
			"Comment": PacuComment,
			"Keyword": PacuJavascriptKeyword,
			"ReservedWord": PacuJavascriptKeyword,
			"FutureReservedWord": PacuJavascriptKeyword,
			"Identifier": PacuOperator,
			"DecimalLiteral": PacuNumber,
			"HexIntegerLiteral": PacuNumber,
			"StringLiteral": PacuStringLiteral,
			"EscapeSequence": PacuEscape,
			"BackslashSequence": PacuBackslashSequence,
			"RegularExpressionLiteral": PacuRegularExpression,
			"Punctuator" : PacuPunctuator,
			"DivPunctuator" : PacuPunctuator
		},
		"xml": {
			"Comment": PacuHtmlComment,
			"TagName": PacuTagName,
			"TagOpen": PacuTagOpen,
			"TagClose": PacuTagClose,
			"AttributeName": PacuTagAttribute,
			"AttributeValue": PacuTagValue,
			"ScriptTagName": PacuTagOther
		},
		"erb": {
			"ErbComment": PacuComment,
			"ErbStart": PacuErbTag,
			"ErbEnd": PacuErbTag
		},
		"cxx": {
			"BlockComment": PacuBlockComment,
			"LineComment": PacuComment,
			"PreprocessingComment": PacuComment,
			"Preprocessing": PacuPreprocessing,
			"EscapedChar": PacuEscape,
			"String": PacuString,
			"ObjcEscapedChar": PacuEscape,
			"ObjcString": PacuString,
			"Keyword": PacuKeyword,
			"TypeKeyword": PacuKeyword,
			"QtKeyword": PacuKeyword,
			"ObjcKeyword": PacuObjcKeyword,
			"Integer": PacuInteger,
			"Float": PacuFloat,
			"Char": PacuChar,
			"Punctuator" : PacuPunctuator
		},
		"bash": {
			"Comment": PacuComment,
			"SingleQuoted": PacuString,
			"DoubleQuoted": PacuString,
			"Document": PacuDocument,
			"EscapedChar": PacuEscape,
			"Expansion": PacuInterpolation,
			"Operator": PacuOperator,
			"Builtin": PacuBuiltinConstant,
			"Reserved": PacuKeyword,
			"Integer": PacuInteger
		}
	},
	
	editor: {
		foreground: PacuEditorFG,
		background: PacuEditorBG,
		cursor: PacuEditorCursor,
		lineNumbers: "#808080",
		lineNumbersBright: "#000",
		lineNumbersBackground: "#F2F2F2",
		lineNumbersBackgroundBright: "#E5E5E5",
		selection: PacuEditorSelection,
		match: PacuEditorMatch,
		bracketMatch: PacuEditorBracketMatch,
		currentLine: PacuEditorCurrentLine
	}
};
