// Ruby Blue v0.1.0
// This theme is generated by a converter script.
// Original Textmate Theme: "Ruby Blue" copyright by John W. Long.
// The conversion is still incomplete. Any suggestions or any problems,
// please contact me at yanyu [at] cyblogic [dot] com.
// More at http://github.com/yanyu/rubyblue

GHEditorFG = '#FFFFFF';
GHEditorBG = '#121E31';
GHEditorCursor = '#fff';
GHEditorSelection = '#38566F';
GHEditorMatch = '#787878';
GHEditorBracketMatch = GHEditorMatch;
GHEditorCurrentLine = '#253E5A';
GHComment = '#428BDD';
GHBlockComment = '#438AD7';
GHHtmlComment = '#428BDD';
GHStringLiteral = '#E2CE00';
GHRegularExpression = '#CA4344';
GHInterpolation = '#468434';
GHRubyInterpolation = '#468434';
GHDocument = '#1DC116';
GHNumber = '#EDDD3D';
GHRubyNumber = '#EDDD3D';
GHInteger = '#EDDD3D';
GHFloat = '#EDDD3D';
GHKeyword = '#F8BB00';
GHJavascriptKeyword = '#F8BB00';
GHObjcKeyword = '#F8BB00';
GHPreprocessing = '#FFFFFF';
GHRubyClassName = '#FFFFFF';
GHConstantName = '#8AA6C1';
GHBuiltinConstant = '#8AA6C1';
GHCharacterConstant = '#8AA6C1';
GHEscape = '#EDDD37';
GHBlock = '#FFFFFF';
GHSymbol = '#B53B3C';
GHVariable = '#FFFFFF';
GHRubyVariable = '#FFFFFF';
GHRubyInstanceVariable = '#FFFFFF';
GHRubyClassVariable = '#FFFFFF';
GHRubyGlobalVariable = '#FFFFFF';
GHPunctuator = '#FFFFFF';
GHOperator = '#8AA6C1';
GHArrayBracket = '#FFFFFF';
GHBackslashSequence = '#FFFFFF';
GHTag = '#FFFFFF';
GHTagName = '#FFFFFF';
GHTagOpen = '#FFFFFF';
GHTagClose = '#FFFFFF';
GHTagOther = '#FFFFFF';
GHTagAttribute = '#FFFFFF';
GHTagValue = '#FFFFFF';
GHErbTag = '#FFFFFF';

charcoal.themes["Ruby Blue"] =
{
	displayName: "Ruby Blue",

	layers: {
		"ruby": {
			"Comment": GHComment,
			"BlockComment": GHBlockComment,
			"Block": GHBlock,
			"Interpolation": GHInterpolation,
			"String": GHStringLiteral,
			"Document": GHDocument,
			"Keyword": GHKeyword,
			"DeclarationKeyword": GHKeyword,
			"Builtin": GHBuiltinConstant,
			"LocalName": GHRubyVariable,
			"MemberName": GHRubyInstanceVariable,
			"ClassMemberName": GHRubyClassVariable,
			"ClassName": GHRubyClassName,
			"ConstantName": GHConstantName,
			"GlobalName": GHRubyGlobalVariable,
			"Symbol": GHSymbol,
			"OpeningBracket": GHArrayBracket,
			"ClosingBracket": GHArrayBracket,
			"Float": GHFloat,
			"Integer": GHInteger,
			"Operator": GHOperator,
			"EscapeSequence": GHEscape
		},
		"python": {
			"Comment": GHComment,
			"String": GHStringLiteral,
			"Keyword": GHKeyword,
			"Identifier": GHKeyword,
			"Operator": GHOperator,
			"Float": GHFloat,
			"Integer": GHInteger
		},
		"javascript": {
			"Comment": GHComment,
			"Keyword": GHJavascriptKeyword,
			"ReservedWord": GHJavascriptKeyword,
			"FutureReservedWord": GHJavascriptKeyword,
			"Identifier": GHOperator,
			"DecimalLiteral": GHNumber,
			"HexIntegerLiteral": GHNumber,
			"StringLiteral": GHStringLiteral,
			"EscapeSequence": GHEscape,
			"BackslashSequence": GHBackslashSequence,
			"RegularExpressionLiteral": GHRegularExpression,
			"Punctuator" : GHPunctuator,
			"DivPunctuator" : GHPunctuator
		},
		"xml": {
			"Comment": GHHtmlComment,
			"TagName": GHTagName,
			"TagOpen": GHTagOpen,
			"TagClose": GHTagClose,
			"AttributeName": GHTagAttribute,
			"AttributeValue": GHTagValue,
			"ScriptTagName": GHTagOther
		},
		"erb": {
			"ErbComment": GHComment,
			"ErbStart": GHErbTag,
			"ErbEnd": GHErbTag
		},
		"cxx": {
			"BlockComment": GHBlockComment,
			"LineComment": GHComment,
			"PreprocessingComment": GHComment,
			"Preprocessing": GHPreprocessing,
			"EscapedChar": GHEscape,
			"String": GHStringLiteral,
			"ObjcEscapedChar": GHEscape,
			"ObjcString": GHStringLiteral,
			"Keyword": GHKeyword,
			"TypeKeyword": GHKeyword,
			"QtKeyword": GHKeyword,
			"ObjcKeyword": GHObjcKeyword,
			"Integer": GHInteger,
			"Float": GHFloat,
			"Char": GHCharacterConstant,
			"Punctuator" : GHPunctuator
		},
		"bash": {
			"Comment": GHComment,
			"SingleQuoted": GHStringLiteral,
			"DoubleQuoted": GHStringLiteral,
			"Document": GHDocument,
			"EscapedChar": GHEscape,
			"Expansion": GHInterpolation,
			"Operator": GHOperator,
			"Builtin": GHBuiltinConstant,
			"Reserved": GHKeyword,
			"Integer": GHInteger
		}
	},
	
	editor: {
		foreground: GHEditorFG,
		background: GHEditorBG,
		cursor: GHEditorCursor,
		lineNumbers: "#808080",
		lineNumbersBright: "#000",
		lineNumbersBackground: "#F2F2F2",
		lineNumbersBackgroundBright: "#E5E5E5",
		selection: GHEditorSelection,
		match: GHEditorMatch,
		bracketMatch: GHEditorBracketMatch,
		currentLine: GHEditorCurrentLine
	}
};
